[theme]
primaryColor = "#1db954"  # Spotify green
backgroundColor = "#141414"  # Dark mode
secondaryBackgroundColor = "#1e1e1e"  # Slightly lighter dark
textColor = "#FFFFFF"  # White text
font = "sans serif"