[theme]
primaryColor = "#1db954"  # Spotify green
backgroundColor = "#121212"  # Dark mode
secondaryBackgroundColor = "#191414"  # Slightly lighter dark
textColor = "#FFFFFF"  # White text
font = "sans serif"